language: minimal

before_script:
  - echo "deb http://deb.debian.org/debian/ bullseye main contrib non-free" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://deb.debian.org/debian/ bullseye main contrib non-free" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://deb.debian.org/debian/ buster-backports main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get -y --allow-unauthenticated install debian-archive-keyring
  - sudo apt-key update
  - sudo apt-get -qq update
  - sudo apt-get -y install linux-source-5.4
  - sudo apt-get -y install build-essential fakeroot
  - sudo apt-get -y build-dep linux
  - tar xafk /usr/src/linux-source-5.4.tar.xz

script:
  - ./build.sh
