language: minimal

before_script:
  - echo "deb http://ftp.ru.debian.org/debian/ bullseye main contrib non-free" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://ftp.ru.debian.org/debian/ bullseye main contrib non-free" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get -y install build-essential fakeroot
  - sudo apt-get -y build-dep linux
  - sudo apt-get -y install linux-source-5.4
  - tar xafk /usr/src/linux-source-5.4.tar.xz

script:
  - ./build.sh
